site_name: py-bopa
site_description: Documentation for py-bopa
site_url: https://diegoglezsu.github.io/py-bopa/
repo_url: https://github.com/diegoglezsu/py-bopa
repo_name: diegoglezsu/py-bopa

theme:
  name: material
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - index.md
  - getting-started.md
  - development.md
  - API Reference:
      - py-bopa: api/py-bopa.md
  - Use Cases:
      - use_cases/py-bopa.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
